-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `lakehouse`;
USE SCHEMA `default`;

-- COMMAND ----------

SELECT * from samples.wanderbricks.users

-- COMMAND ----------

select * from read_files("abfss://raw@adlsnaval123.dfs.core.windows.net/ecom/sales")

-- COMMAND ----------

create schema if not exists lakehouse.shanthapriya_bronze  managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/shanthapriya'


-- COMMAND ----------

create schema if not exists lakehouse.shanthapriya_silver managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/shanthapriya'

-- COMMAND ----------

create schema if not exists lakehouse.shanthapriya_gold  managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/shanthapriya'

-- COMMAND ----------

-- MAGIC %md
-- MAGIC merge into target 
-- MAGIC using soucre
-- MAGIC matching condition
-- MAGIC when matched then update set *
-- MAGIC when not matched then insert *
-- MAGIC --select * from lakehouse.naval_bronze.sales
-- MAGIC

-- COMMAND ----------

select * except(`__START_AT`,`__END_AT`)  from lakehouse.shanthapriya_silver.customers_scd2 where `__END_AT` is not null

-- COMMAND ----------

select * except(`__START_AT`,`__END_AT`) from lakehouse.shanthapriya_silver.customers_scd2 where `__END_AT` is null

-- COMMAND ----------

SELECT
  c.customer_id,
  c.customer_name,
  c.customer_email,
  c.customer_city,
  c.customer_state,
  ROUND(SUM(s.total_amount)) AS total_amount
FROM
  lakehouse.naval_silver.sales_cleaned s
JOIN
  lakehouse.naval_gold.customers_active c
ON
  s.customer_id = c.customer_id
GROUP BY
  c.customer_id,
  c.customer_name,
  c.customer_email,
  c.customer_city,
  c.customer_state
ORDER BY
  total_amount DESC
LIMIT 3

-- COMMAND ----------

select customer_id, round(sum(total_amount)) as total_amount from lakehouse.shanthapriya_silver.sales_cleaned group by customer_id order by total_amount desc limit 5
